name: Create and publish a Docker image

on:
   push
#  push:
#    branches:
#      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-renv

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v25

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"

      - name: Run step when a file changes
        if: contains(steps.changed-files.outputs.modified_files, 'Scripts/dependencies.R')
        run: |
          echo "Your Scripts/dependencies.R file has been modified."

      - name: Build and push Docker image
        if: contains(steps.changed-files.outputs.modified_files, 'Scripts/dependencies.R')
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }}
